FROM node:6.14.2
COPY server.js .
CMD node server.js

# docker build [OPTIONS] [ARGUMENTS] 
# docker build -f Dockerfile -t helloworld:1.0 .

# docker run [OPTIONS] IMAGE [COMMAND] [ARG...]
# docker run --name helloworld -d -p 8080:8080 helloworld:1.0
